---
abstract: "Easy way to stuff \"status\" messages into your stash"
author:
  - 'Devin Austin <dhoss@cpan.org>'
generated_by: 'Dist::Zilla version 1.093000'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-MessageSmush
requires:
  Catalyst: 5.8
  Moose: "\"\""
  Moose::Role: "\"\""
  Test::Simple: 0.88
version: 0.01.1
